<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="OpenTelemetry" Version="1.9.0" />
    <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.9.0-beta.1" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.9.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.13.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.13.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Process" Version="1.0.0-alpha.6" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.13.0" />
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
    <PackageReference Include="ZstdSharp.Port" Version="0.7.1" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="../../src/MetricsPush/**/*.cs" LinkBase="MetricsPush" />
    <Compile Include="../../src/Compress/**/*.cs" LinkBase="Compress" />
    <Compile Include="../../src/Common/**/*.cs" LinkBase="Common" />
    <Compile Include="../../src/ConsoleLogger/**/*.cs" LinkBase="ConsoleLogger" />
  </ItemGroup>
</Project>
